adding changed css for pinned blog
DevCom-IITB/instiapp-angular pull request #91
Opened 2021-07-18 15:13 UTC by harsh-kr-jha

adding CSS and HTML code to switch between class when pinned status change

2021-07-19 17:58 UTC, pulsejet requested changes
Just some comments on code style, upto the maintainer to enforce or not.

Just curious, what are you trying to do here?

2021-07-19 17:58 UTC, pulsejet commented on src/app/page/blog/blog.component.css
> +
Why is there a newline here?

2021-07-19 17:58 UTC, pulsejet commented on src/app/page/blog/blog.component.css
> +    /* background-color: rgb(151, 178, 212); */
Commented code is code smell

2021-07-19 17:58 UTC, pulsejet commented on src/app/page/blog/blog.component.css
> +    font-weight: bold;
Wrong indentation

2021-07-19 17:58 UTC, pulsejet commented on src/app/page/blog/blog.component.css
> +
More newlines...

2021-07-25 06:03 UTC, e-aakash commented on src/app/page/blog/blog.component.html
> +                 'feed-card': item.pin_unpin== 0,
You may have to update this based on renamed value in backend. (`pin_unpin` -> `pinned`)

2021-08-04 14:51 UTC, e-aakash commented
> Just curious, what are you trying to do here?

@pulsejet : Placement blog has introduced a new feature, for pinning certain blog. They asked for similar feature in instiapp blogs as well. The backend change was introduced in https://github.com/wncc/instiapp-api/pull/460 and https://github.com/wncc/instiapp-api/pull/461 
This pr is for visual highlighting the pinned blog post in webapp.

2022-06-08 18:32 UTC, closed without merging